### ISSUE TITLE
Add --help argument

### ISSUE THREAD

**Issue by lukasvdberk** [lukasvdberk/spotify_song_changer_cli#1]

**Comment by abcdan** [comment]
arguemtn

**Comment by lukasvdberk** [comment]
I don't know what you'r talking about

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/117859651-91bbbf00-b28f-11eb-8216-a3a1a014812a.png)
THIS

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/117859678-9c765400-b28f-11eb-9836-530b9f629867.png)

**Comment by lukasvdberk** [comment]
Thats kinda sus

**Comment by lukasvdberk** [comment]
Wasn't me

**Comment by abcdan** [comment]
![1](https://user-images.githubusercontent.com/15849319/117859711-a7c97f80-b28f-11eb-99dd-a73360a61cd3.png)
