### ISSUE TITLE
add floopnator

### ISSUE THREAD

**Issue by abcdan** [lukasvdberk/spotify_song_changer_cli#6]
i think that a floopynator would really benefit this project.

**Comment by lukasvdberk** [comment]
I think the world would benefit if you would just not wake up in the morning.

**Comment by abcdan** [comment]
gast, ik heb meer sterren

**Comment by lukasvdberk** [comment]
gast, heb jij een niet gerealiseerde half werkende boodschappen app? dacht het niet he

**Comment by abcdan** [comment]
Je bedoelt deze? https://myfridgefood.com/ 
oh wacht 😎 die is in production

**Comment by abcdan** [comment]
floppynator
